るびまの校正ルールに対する簡易的なフォーマッターの追加
rubima/magazine.rubyist.net pull request #440
Opened 2023-06-07 21:39 UTC by takkanm

編集向けに https://github.com/rubima/magazine.rubyist.net/blob/master/doc/editing_policy.md の 一部ルールを確認しながら変更できるツールを用意しました。

- 半角文字列前後の空白
- 不要な空白

経験上、この二つのルールで rubima-lint のエラーの半数は消せるのではないかと思います。

オートコレクトさせたいのですが、固有名詞でこのルールにあてられないものもあり、
スクリプト内では確認しながらの変更としています。

```shell
$ ruby editing_tools/formatter.rb 対象ファイル
```

2023-06-07 22:12 UTC, amatsuda commented
trimed, formated

2023-06-08 00:03 UTC, kakutani commented
わー。例外ケースのことがすぐに浮かんじゃってすぐ「この記事だけやればいい…人間は最も精密な機械…」ってなっちゃうからありがてえありがてえ

2023-06-08 14:18 UTC, kakutani requested changes
スペルミスだけ直しておくとよさそう

2023-06-08 14:18 UTC, kakutani commented on editing_tools/formatter.rb
> +      puts "#{formated_message}: line [#{@line_no}]:"
```suggestion
      puts "#{formatted_message}: line [#{@line_no}]:"
```

https://github.com/rubima/magazine.rubyist.net/pull/440#issuecomment-1581582284

2023-06-08 14:18 UTC, kakutani commented on editing_tools/formatter.rb
> +    def formated_message
``` suggestion
    def formatted_message
```
https://github.com/rubima/magazine.rubyist.net/pull/440#issuecomment-1581582284

2023-06-08 14:18 UTC, kakutani commented on editing_tools/formatter.rb
> +    def formated_message
```suggestion
    def formatted_message
```
https://github.com/rubima/magazine.rubyist.net/pull/440#issuecomment-1581582284

2023-06-08 14:18 UTC, kakutani commented on editing_tools/formatter.rb
> +    formated_file = execute_format!
```suggestion
    formatted_file = execute_format!
```

2023-06-08 14:18 UTC, kakutani commented on editing_tools/formatter.rb
> +    FileUtils.copy_file formated_file.path, @src_file_path
```suggestion
    FileUtils.copy_file formatted_file.path, @src_file_path
```

2023-06-08 14:18 UTC, kakutani commented on editing_tools/formatter.rb
> +    def convert_line(trimed = '')
```suggestion
    def convert_line(trimmed = '')
```
https://github.com/rubima/magazine.rubyist.net/pull/440#issuecomment-1581582284

2023-06-08 14:18 UTC, kakutani commented on editing_tools/formatter.rb
> +      @line.gsub(INVALID_BLANK, trimed)
```suggestion
      @line.gsub(INVALID_BLANK, trimmed)
```
https://github.com/rubima/magazine.rubyist.net/pull/440#issuecomment-1581582284

2023-06-09 00:56 UTC, kakutani commented on editing_tools/formatter.rb
> +      @line.gsub(INVALID_BLANK, trimed)
trimmedもたのむ! 🙏

2023-06-10 00:31 UTC, kakutani approved these changes

2023-06-10 00:33 UTC, merged

2023-06-10 14:29 UTC, kakutani commented
@takkanm 雑にマージしちゃったけど、たぶんお手元の`rubima-lint.rb`もpushしてもらう必要がありそう。
https://github.com/rubima/magazine.rubyist.net/blob/5ba1118d11beedede14a51f0c4146f017c7920c0/editing_tools/rubima-lint.rb に`Rules`は無いっぽい。

```
editing_tools/formatter.rb:9:in `<class:BaseFormatter>': uninitialized constant RubimaLint::Rules (NameError)

    include RubimaLint::Rules
                      ^^^^^^^
	from editing_tools/formatter.rb:8:in `<class:RubimaFomatter>'
	from editing_tools/formatter.rb:7:in `<main>'
```