0063:  Rails Girls Tokyo 15th 開催レポート
rubima/magazine.rubyist.net pull request #443
Opened 2023-06-10 07:12 UTC by ericgpks

Rails Girls Tokyo 15th の開催レポートです

2023-06-10 14:47 UTC, kakutani commented on articles/0063/_posts/0063-RailsGirlsTokyo15thReport.md
> +tags: 0063 RailsGirlsTokyo15thReport
[記事先頭のテンプレート](https://github.com/rubima/magazine.rubyist.net/blob/master/doc/writing_process.md#%E6%9B%B8%E5%BC%8F)の説明によれば:
> * tagsについては、号数の他に種別を記してください。
>   * 種別は、記事名と同じですが、地域Ruby会議の場合はregionalRubyKaigiも指定してください。
>   * このtagで指定した内容に応じてバックナンバーの記事一覧を生成しています。このため、大文字小文字も厳密に区別します。

とのことなので、たとえばRGの開催レポートでまとめるなら、"railsGirls"とかがいいのかな、と思ったのですが
[0062のRG Tokyo 14thの開催レポート](https://github.com/rubima/magazine.rubyist.net/blob/master/articles/0062/_posts/2023-04-30-0062-RailsGirlsTokyo14thReport.md?plain=1#L5)も、分野じゃなくて個別開催を`tags`に入れているので分野としては意味がなさそう。
テンプレの説明でのタグ名がlowerCamelCaseである必然性もわかってないのですが、さしあたってどうするのがいいですかねえ @takkanm 

関連して「分野別目次」も現状の運用はどうなっているのか、なにもわからない…。

2023-06-10 14:52 UTC, kakutani commented
@ericgpks ファイル名について、「[るびまに記事を追加する](https://github.com/rubima/magazine.rubyist.net/blob/master/doc/writing_process.md#%E3%82%8B%E3%81%B3%E3%81%BE%E3%81%AB%E8%A8%98%E4%BA%8B%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B)」にあるように:
> 記事は、articles/号数/_posts/yyyy-mm-dd-号数-記事名.mdとして作成してください。
と修正してほしいです。
…といっても、
> ファイル名にあるyyyymmddの部分は、号数のリリース予定日です。これはるびま編集部が決めます。
となっているので、どうすればいいんだ…。 @takkanm 
そして、この命名規約は何かに影響するんでしょうか。
Jekyll的に `/articles/0063/` で一覧されるためには日付を揃える必要があったりするんでしょうか…(調べてない)。
現時点では、ファイル名がこの規約(`yyyy-mm-dd-号数-記事名.md`)に従っていないと、Jekyllで`/articles/0063/`から見えない、ということだけはわかりました。

2023-06-10 14:57 UTC, kakutani commented
off-topic だけど、記事ファイル名のprefixに日付や号数って必要なんですかねえ。

* 日付はまあJekyllでblogっぽく見せるのに必要なのか? …と思ったけど番のslugに日付は出てきてないように見える…
* 号数は `https://magazine.rubyist.net/articles/0062/0062-TochigiRubyKaigi09Report.html` みたいになるから冗長なような…(原稿ファイルも号数ディレクトリの下だしな…)

と、見始めると気になるポイントがいくつかある…(Discussionにもっていけばいいのかな)

2023-06-11 13:40 UTC, takkanm commented on articles/0063/_posts/0063-RailsGirlsTokyo15thReport.md
> +tags: 0063 RailsGirlsTokyo15thReport
62 号までにリリースされている RailsGrils の記事が 7 件あるので、RailsGirls の記事を分野別記事にまとめたほうがいいと感じています。
で、分野別目次に載せる最初の一歩は https://github.com/rubima/magazine.rubyist.net/blob/5ba1118d11beedede14a51f0c4146f017c7920c0/articles/backnumber/_posts/2000-01-01-backnumber.md を編集し、過去記事に同一のタグを振ることになります。これは、別 issue で行いましょう。

2023-06-11 13:41 UTC, takkanm commented on articles/0063/_posts/0063-RailsGirlsTokyo15thReport.md
> +tags: 0063 RailsGirlsTokyo15thReport
@ericgpks とうことで、今回はこのタグの部分に `RailsGirlsReport` というのを追加しておいてもらえますか？

2023-06-11 14:00 UTC, takkanm commented
ファイル名の日付について。雑な印象としては必要ないとは思うのですが、どこかしらビルドがこけるのかなという気がしています。
なので、今回のファイル名はこのままにしておいて、merge 時におかしいところがでたら、ビルドシステム直す or ファイル名直すでいいんじゃないかと思うんですが、どうでしょう > @ericgpks @kakutani

2023-06-11 14:01 UTC, takkanm approved these changes
GH Actions が動くようにするために approve を押します

2023-06-12 10:28 UTC, ericgpks commented on articles/0063/_posts/0063-RailsGirlsTokyo15thReport.md
> +tags: 0063 RailsGirlsTokyo15thReport
@takkanm タグ追加しました！

2023-06-13 13:38 UTC, kakutani commented on articles/0063/_posts/0063-RailsGirlsTokyo15thReport.md
> +tags: 0063 RailsGirlsTokyo15thReport
`RailsGirlsTokyo15thReport` は不要に思えます(「分野」としては機能しなさそう)

2023-06-13 13:43 UTC, kakutani commented
> GH Actions が動くようにするために approve を押します

前はローカルで見えなかった気がしたんだけど、なんか見えるようになったw
http://localhost:4000/articles/0063/0063-RailsGirlsTokyo15thReport.html
![image](https://github.com/rubima/magazine.rubyist.net/assets/2160/f95572d4-9186-492f-b44d-bd48da57ee8c)

2023-06-13 13:52 UTC, kakutani requested changes
体裁の観点で気になるところをコメントしました!(主にheadingと画像)

2023-06-13 13:52 UTC, kakutani commented on articles/0063/_posts/0063-RailsGirlsTokyo15thReport.md
> +### Tokyo15th 開催のきっかけ
```suggestion
## Tokyo15th 開催のきっかけ
```

headingがひとつズレていると思います。

2023-06-13 13:52 UTC, kakutani commented on articles/0063/_posts/0063-RailsGirlsTokyo15thReport.md
> +### 感染対策について
```suggestion
## 感染対策について
```

ここもheading 2かな。

2023-06-13 13:52 UTC, kakutani commented on articles/0063/_posts/0063-RailsGirlsTokyo15thReport.md
> +### ワークショップの内容
```suggestion
## ワークショップの内容
```

ここも2かな。

2023-06-14 02:39 UTC, ericgpks commented on articles/0063/_posts/0063-RailsGirlsTokyo15thReport.md
> +tags: 0063 RailsGirlsTokyo15thReport
`RailsGirlsTokyo15thReport` は削除しました

2023-06-14 02:49 UTC, ericgpks commented on articles/0063/_posts/0063-RailsGirlsTokyo15thReport.md
> +Rails Girls のワークショップは、プログラミング未経験の方を対象に、環境構築〜Rails アプリの作成・公開までを行います。 参加者の中には PC に慣れていない方もいるため、さまざまな躓きポイントをコーチがサポートするには、オフラインで開催するのが一番です。 そのため今回も会場をお借りしてオフラインで開催しました。
ありがとうございます！記号ではなくして、スペースの有無を揃えたかったので修正しました！

2023-06-14 02:49 UTC, ericgpks commented
@kakutani 
レビューありがとうございます！heading と画像、タグなど修正しました！

2023-06-17 08:09 UTC, ericgpks commented
ファイル名に `yyyy-mm-dd` をつけたら私もローカルで記事が見れるようになりました 🙌🏻

2023-06-17 08:09 UTC, ericgpks commented on articles/0063/_posts/0063-RailsGirlsTokyo15thReport.md
> +<img src="{{base}}{{site.baseurl}}/images/0063-RailsGirlsTokyo15thReport/workshop.jpg" width="700px">
修正しました 🙇🏻

2023-06-20 14:19 UTC, kakutani commented on articles/0063/_posts/0063-RailsGirlsTokyo15thReport.md
> +<img src="{{base}}{{site.baseurl}}/images/0063-RailsGirlsTokyo15thReport/workshop.jpg" width="700px">
[fbb52d1](https://github.com/rubima/magazine.rubyist.net/pull/443/commits/fbb52d16764df2b132c31d1d349327ab822e4032) で表示を確認しました!

2023-06-20 14:19 UTC, kakutani approved these changes

2023-06-21 02:22 UTC, merged

2023-06-21 02:22 UTC, kakutani commented
🚀

2023-06-21 03:10 UTC, ericgpks commented
レビューやリリース、ありがとうございました！